### ISSUE TITLE
I want to know. How to convert Ashita to windower 4 for use in addons

### ISSUE THREAD

**Issue by jia900212** [ThornyFFXI/mobdb#12]
As the title indicates, how to transfer to use on windower4, how to change the operation.

**Comment by ThornyFFXI** [comment]
Short version: You can't.

Long version:  Windower and Ashita APIs are completely different.  You can reuse some sections of the lua, but since windower has no equivalent to IMGUI you would need to write a relatively large amount of code to mimic any imgui functionality(such as config windows, or in mobdb's case the entire display element).  If you are fluent in lua, you're almost better off starting from scratch than trying to port anything utilizing IMGUI from Ashita4 to Windower.

**Comment by jia900212** [comment]
I don't have the skill, because I don't understand, thank you for your answer. Just asking for an answer
