### ISSUE TITLE
$job / $joblevel not displaying jobs on enemies

### ISSUE THREAD

**Issue by Chibloom** [ThornyFFXI/mobdb#8]
MobFormat='$name$joblevel $job $id $dynamic $aggro$LB$physmagic immune: $immunity',
installs have not been touched other than swapping to old icons

mob tested on Sauromugue Champaign, this is zone id 120; similar results on Yagudo Interrogator, Yagudo Votary, Yagudo Priest, and Tabar Beak.
V1.02 img ![v1 02](https://user-images.githubusercontent.com/86545774/212206417-70c4b592-7d7e-4a0f-b0d3-625cd40f3229.PNG)
V1.05 img ![V1 05](https://user-images.githubusercontent.com/86545774/212206420-71e364e2-342e-48f7-a0f9-35aab3eee5e1.PNG)

$joblevel works as intended on players
sry if i missed something, its my first time using github

**Comment by ThornyFFXI** [comment]
This is most likely caused by inconsistancies in the dataset generation.  I have no intention of making mobdb anything near fully accurate, as the game has an insane amount of monsters and no official source for this data, which is why it includes tooling to generate accurate data from your server's SQL files(may or may not be available for a given server, but the admin have them).

That said, it does seem likely some sort of mistake resulted in the job being lost, so I will take a look at this specific issue shortly.

**Comment by ThornyFFXI** [comment]
I should also note that v1.02 did not have the dynamic/static token, so I am unsure how the first image is  from 1.02.  But, I will update as soon as I am able to find more information on the issue itself.

**Comment by ThornyFFXI** [comment]
Confirmed that latest version was not properly generating job data, fixed generation process and bundled dataset in 1.08.

**Comment by Chibloom** [comment]
> I should also note that v1.02 did not have the dynamic/static token, so I am unsure how the first image is from 1.02. But, I will update as soon as I am able to find more information on the issue itself.

that is a v1.02, its the same mobformat being used just that the $ was being omitted

well there be any plan to make an interface v4.14 btw?

**Comment by ThornyFFXI** [comment]
Do not comment on closed issues, or use github for casual chat.  You can join the ashita discord for things like this.

Since addons are not compiled and the 4.15 version does not use anything specific to 4.15 it can be loaded and used on 4.14.
